[vc_row container_type="content-full" padding="padding-no" padding_top="0" padding_bottom="0" fixed_height="0" bgtype="bg-default" bgcolor="#ffffff" bgparallax="bg-parallax" map_type="ROADMAP" map_zoom="12" map_scroll="false" map_drag="false" map_zoom_control="false" map_disable_doubleclick="true" map_streetview="false" bgmask_color="#000000" bgmask_color_opacity="0.9" bgimage_position="top left" bgimage_repeat="no-repeat" bgimage_attach="scroll" css_animation_delay="0"][vc_column width="1/1"][md_revslider alias="slider-01"][/vc_column][/vc_row][vc_row container_type="content-fixed" padding="padding-medium" padding_top="0" padding_bottom="0" fixed_height="0" bgtype="bg-custom-color" bgcolor="#ffffff" bgparallax="bg-parallax" map_type="ROADMAP" map_zoom="12" map_scroll="false" map_drag="false" map_zoom_control="false" map_disable_doubleclick="true" map_streetview="false" bgmask_color="#000000" bgmask_color_opacity="0.9" bgimage_position="top left" bgimage_repeat="no-repeat" bgimage_attach="scroll" css_animation_delay="0"][vc_column width="1/1"][vc_row_inner][vc_column_inner width="1/3"][md_box_icon icon_family="typicons" icon_fontawesome="icon-glass" icon_typicons="typcn-heart-outline" icon_entypo="entypo-note" icon_lineicons="lineicon-banknote" icon_position="left" icon_style="style-normal" icon_color="#16a085" icon_bg_color="#ffffff" icon_border_color="#16a085" icon_size="24" css_animation_delay="0"]
<h4>UNIQUE STYLE</h4>
Fusce sit amet quam massa. Fusce in ultricies nibh. Pellentesque est velit, faucibus et venenatis et, pharetra et nulla aenean.[/md_box_icon][/vc_column_inner][vc_column_inner width="1/3"][md_box_icon icon_family="typicons" icon_fontawesome="icon-glass" icon_typicons="typcn-beaker" icon_entypo="entypo-note" icon_lineicons="lineicon-banknote" icon_position="left" icon_style="style-normal" icon_color="#16a085" icon_bg_color="#ffffff" icon_border_color="#16a085" icon_size="24" css_animation_delay="0"]
<h4>PAGE BUILDER</h4>
Fusce sit amet quam massa. Fusce in ultricies nibh. Pellentesque est velit, faucibus et venenatis et, pharetra et nulla aenean.[/md_box_icon][/vc_column_inner][vc_column_inner width="1/3"][md_box_icon icon_family="typicons" icon_fontawesome="icon-glass" icon_typicons="typcn-document-text" icon_entypo="entypo-note" icon_lineicons="lineicon-banknote" icon_position="left" icon_style="style-normal" icon_color="#16a085" icon_bg_color="#ffffff" icon_border_color="#16a085" icon_size="24" css_animation_delay="0"]
<h4>FULLY DOCUMENTED</h4>
Fusce sit amet quam massa. Fusce in ultricies nibh. Pellentesque est velit, faucibus et venenatis et, pharetra et nulla aenean.[/md_box_icon][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row container_type="content-full" padding="padding-custom" padding_top="80" padding_bottom="0" fixed_height="0" bgtype="bg-custom-color" bgcolor="#f4f4f4" section_arrow="arrow-down" bgparallax="bg-parallax" map_type="ROADMAP" map_zoom="12" map_scroll="false" map_drag="false" map_zoom_control="false" map_disable_doubleclick="true" map_streetview="false" bgmask_color="#000000" bgmask_color_opacity="0.9" bgimage_position="top left" bgimage_repeat="no-repeat" bgimage_attach="scroll" css_animation_delay="0"][vc_column width="1/1"][md_special_heading style="style-2" border_color="dark" fontweight="normal" color="#444444" fontsize="24" lineheight="32" css_animation_delay="0" text_align="textaligncenter"]SHOWCASE YOUR WORKS WITH FUN![/md_special_heading][md_portfolio orderby="ID" order="DESC" items_cols="3" category="all" style="alternative" filter_style="light" wall_mode="wall-mode" posts_per_page="12" css_animation_delay="0" carousel_navigation="true" carousel_pagination="true" carousel="true"][/vc_column][/vc_row][vc_row container_type="content-fixed" padding="padding-large" padding_top="0" padding_bottom="0" fixed_height="0" bgtype="bg-custom-color" bgcolor="#ffffff" bgparallax="bg-parallax" map_type="ROADMAP" map_zoom="12" map_scroll="false" map_drag="false" map_zoom_control="false" map_disable_doubleclick="true" map_streetview="false" bgmask_color="#000000" bgmask_color_opacity="0.9" bgimage_position="top left" bgimage_repeat="no-repeat" bgimage_attach="scroll" css_animation_delay="0"][vc_column width="1/1"][vc_row_inner][vc_column_inner width="5/12"][md_single_image size="md-full" css_animation="fadeInLeft" image="4593" css_animation_delay="0"][/vc_column_inner][vc_column_inner width="1/12"][/vc_column_inner][vc_column_inner width="1/2"][md_blank_space height="30"][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-big58" icon_position="left" icon_style="style-normal" icon_color="#16a085" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="0" css_animation="fadeInRight"]
<h4>INFINITE LAYOUTS</h4>
Curabitur eget neque metus. Sed pellentesque accumsan tellus, vel ultricies justo vulputate et. Sed pharetra ligula dolor, vitae molestie sem volutpat quis. Praesent eu convallis tortor. Aenean eu tincidunt urna.[/md_box_icon][md_blank_space height="30"][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-fire" icon_position="left" icon_style="style-normal" icon_color="#16a085" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="300" css_animation="fadeInRight"]
<h4>INCREDIBLE EFFECTS</h4>
Curabitur eget neque metus. Sed pellentesque accumsan tellus, vel ultricies justo vulputate et. Sed pharetra ligula dolor, vitae molestie sem volutpat quis. Praesent eu convallis tortor. Aenean eu tincidunt urna.[/md_box_icon][md_blank_space height="30"][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-note2" icon_position="left" icon_style="style-normal" icon_color="#16a085" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="600" css_animation="fadeInRight"]
<h4>VIDEO&amp;SLIDER BACKGROUNDS</h4>
Curabitur eget neque metus. Sed pellentesque accumsan tellus, vel ultricies justo vulputate et. Sed pharetra ligula dolor, vitae molestie sem volutpat quis. Praesent eu convallis tortor. Aenean eu tincidunt urna.[/md_box_icon][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row container_type="content-fixed" padding="padding-medium" padding_top="0" padding_bottom="0" fixed_height="0" bgtype="bg-custom-color" bgcolor="#171717" bgparallax="bg-parallax" map_type="ROADMAP" map_zoom="12" map_scroll="false" map_drag="false" map_zoom_control="false" map_disable_doubleclick="true" map_streetview="false" bgmask_color="#000000" bgmask_color_opacity="0.9" bgimage_position="top left" bgimage_repeat="no-repeat" bgimage_attach="scroll" css_animation_delay="0"][vc_column width="1/1"][vc_row_inner][vc_column_inner width="1/4"][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-data3" icon_position="top" icon_style="style-normal" icon_color="#16a085" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="0"]
<h4><span style="color: #ffffff;">Advanced Page Builder</span></h4>
<span style="color: #ffffff;">Etiam rhoncus dui id semper convallis. Nunc commodo convallis ante et dictum. Nullam sollicitudin risus.</span>[/md_box_icon][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-lab" icon_position="top" icon_style="style-normal" icon_color="#16a085" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="0"]
<h4><span style="color: #ffffff;">Infinite Layouts</span></h4>
<span style="color: #ffffff;">Etiam rhoncus dui id semper convallis. Nunc commodo convallis ante et dictum. Nullam sollicitudin risus.</span>[/md_box_icon][/vc_column_inner][vc_column_inner width="1/2" text_align="textaligncenter" bgcolor="#ffffff" bgcolor_transparency="100" padding="padding-no" padding_custom="0" css_animation_delay="0"][md_single_image size="large" image="4605" css_animation_delay="0"][/vc_column_inner][vc_column_inner width="1/4"][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-parameters" icon_position="top" icon_style="style-normal" icon_color="#16a085" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="0"]
<h4><span style="color: #ffffff;">Easy to customize</span></h4>
<span style="color: #ffffff;">Etiam rhoncus dui id semper convallis. Nunc commodo convallis ante et dictum. Nullam sollicitudin risus.</span>[/md_box_icon][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-diamons" icon_position="top" icon_style="style-normal" icon_color="#16a085" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="0"]
<h4><span style="color: #ffffff;">WooCommerce Support</span></h4>
<span style="color: #ffffff;">Etiam rhoncus dui id semper convallis. Nunc commodo convallis ante et dictum. Nullam sollicitudin risus.</span>[/md_box_icon][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row container_type="content-fixed" padding="padding-medium" padding_top="0" padding_bottom="0" fixed_height="0" bgtype="bg-custom-color" bgcolor="#ffffff" bgparallax="bg-parallax" map_type="ROADMAP" map_zoom="12" map_scroll="false" map_drag="false" map_zoom_control="false" map_disable_doubleclick="true" map_streetview="false" bgmask_color="#000000" bgmask_color_opacity="0.9" bgimage_position="top left" bgimage_repeat="no-repeat" bgimage_attach="scroll" css_animation_delay="0"][vc_column width="1/1"][vc_row_inner][vc_column_inner width="1/3"][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-like" icon_position="left" icon_style="style-normal" icon_color="#9e9e9e" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="0" css_animation="fadeInUp"]
<h4>AWESOME PORTFOLIO LAYOUTS</h4>
Curabitur eget neque metus. Sed pellentesque accumsan tellus, vel ultricies justo vulputate et. Sed pharetra ligula dolor, vitae molestie sem volutpat quis. Praesent eu convallis tortor. Aenean eu tincidunt urna.[/md_box_icon][/vc_column_inner][vc_column_inner width="1/3"][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-paperclip2" icon_position="left" icon_style="style-normal" icon_color="#9e9e9e" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="300" css_animation="fadeInUp"]
<h4>GOOGLE FONTS SUPPORT</h4>
Curabitur eget neque metus. Sed pellentesque accumsan tellus, vel ultricies justo vulputate et. Sed pharetra ligula dolor, vitae molestie sem volutpat quis. Praesent eu convallis tortor. Aenean eu tincidunt urna.[/md_box_icon][/vc_column_inner][vc_column_inner width="1/3"][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-parameters" icon_position="left" icon_style="style-normal" icon_color="#9e9e9e" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="600" css_animation="fadeInUp"]
<h4>UNLIMITED OPTIONS</h4>
Curabitur eget neque metus. Sed pellentesque accumsan tellus, vel ultricies justo vulputate et. Sed pharetra ligula dolor, vitae molestie sem volutpat quis. Praesent eu convallis tortor. Aenean eu tincidunt urna.[/md_box_icon][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/3"][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-settings3" icon_position="left" icon_style="style-normal" icon_color="#9e9e9e" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="1500" css_animation="fadeInUp"]
<h4>FULLY CUSTOMIZABLE</h4>
Curabitur eget neque metus. Sed pellentesque accumsan tellus, vel ultricies justo vulputate et. Sed pharetra ligula dolor, vitae molestie sem volutpat quis. Praesent eu convallis tortor. Aenean eu tincidunt urna.[/md_box_icon][/vc_column_inner][vc_column_inner width="1/3"][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-small59" icon_position="left" icon_style="style-normal" icon_color="#9e9e9e" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="1200" css_animation="fadeInUp"]
<h4>WOOCOMMERCE SUPPORT</h4>
Curabitur eget neque metus. Sed pellentesque accumsan tellus, vel ultricies justo vulputate et. Sed pharetra ligula dolor, vitae molestie sem volutpat quis. Praesent eu convallis tortor. Aenean eu tincidunt urna.[/md_box_icon][/vc_column_inner][vc_column_inner width="1/3"][md_box_icon icon_family="lineicons" icon_fontawesome="icon-glass" icon_typicons="typcn-adjust-brightness" icon_entypo="entypo-note" icon_lineicons="lineicon-photo3" icon_position="left" icon_style="style-normal" icon_color="#9e9e9e" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="900" css_animation="fadeInUp"]
<h4>REVOLUTION SLIDER INCLUDED</h4>
Curabitur eget neque metus. Sed pellentesque accumsan tellus, vel ultricies justo vulputate et. Sed pharetra ligula dolor, vitae molestie sem volutpat quis. Praesent eu convallis tortor. Aenean eu tincidunt urna.[/md_box_icon][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row container_type="content-full" padding="padding-no" padding_top="0" padding_bottom="0" fixed_height="0" bgtype="bg-custom-color" bgcolor="#ffffff" bgparallax="bg-parallax" map_type="ROADMAP" map_zoom="12" map_scroll="false" map_drag="false" map_zoom_control="false" map_disable_doubleclick="true" map_streetview="false" bgmask_color="#000000" bgmask_color_opacity="0.9" bgimage_position="top left" bgimage_repeat="no-repeat" bgimage_attach="scroll" css_animation_delay="0"][vc_column width="1/1"][vc_row_inner][vc_column_inner width="1/4" bgtype="bg-custom-color" bgcolor="#8e44ad" bgcolor_transparency="100" padding="padding-custom" padding_custom="40" css_animation_delay="0"][md_box_icon icon_family="typicons" icon_fontawesome="icon-glass" icon_typicons="typcn-thumbs-ok" icon_entypo="entypo-note" icon_lineicons="lineicon-banknote" icon_position="top" icon_style="style-normal" icon_color="#ffffff" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="0"]
<h5 style="text-align: center;"><span style="color: #ffffff;">UNLIMITED COLORS</span></h5>
<p style="text-align: center;"><span style="color: #ffffff;">Etiam sollicitudin leo sit amet eleifend molestie. Donec pretium elit eget quam hendrerit, quis molestie nibh pretium. Class aptent taciti sociosqu ad litora torquent per conubia nostra</span></p>
[/md_box_icon][/vc_column_inner][vc_column_inner width="1/4" bgtype="bg-custom-color" bgcolor="#96281b" bgcolor_transparency="100" padding="padding-custom" padding_custom="40" css_animation_delay="0"][md_box_icon icon_family="typicons" icon_fontawesome="icon-glass" icon_typicons="typcn-puzzle-outline" icon_entypo="entypo-note" icon_lineicons="lineicon-banknote" icon_position="top" icon_style="style-normal" icon_color="#ffffff" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="0"]
<h5 style="text-align: center;"><span style="color: #ffffff;">1000+ RETINA ICONS</span></h5>
<p style="text-align: center;"><span style="color: #ffffff;">Etiam sollicitudin leo sit amet eleifend molestie. Donec pretium elit eget quam hendrerit, quis molestie nibh pretium. Class aptent taciti sociosqu ad litora torquent per conubia nostra</span></p>
[/md_box_icon][/vc_column_inner][vc_column_inner width="1/4" bgtype="bg-custom-color" bgcolor="#e87e04" bgcolor_transparency="100" padding="padding-custom" padding_custom="40" css_animation_delay="0"][md_box_icon icon_family="typicons" icon_fontawesome="icon-glass" icon_typicons="typcn-clipboard" icon_entypo="entypo-note" icon_lineicons="lineicon-banknote" icon_position="top" icon_style="style-normal" icon_color="#ffffff" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="0"]
<h5 style="text-align: center;"><span style="color: #ffffff;">FULLY DOCUMENTED</span></h5>
<p style="text-align: center;"><span style="color: #ffffff;">Etiam sollicitudin leo sit amet eleifend molestie. Donec pretium elit eget quam hendrerit, quis molestie nibh pretium. Class aptent taciti sociosqu ad litora torquent per conubia nostra</span></p>
[/md_box_icon][/vc_column_inner][vc_column_inner width="1/4" bgtype="bg-custom-color" bgcolor="#f9690e" bgcolor_transparency="100" padding="padding-custom" padding_custom="40" css_animation_delay="0"][md_box_icon icon_family="typicons" icon_fontawesome="icon-glass" icon_typicons="typcn-eye-outline" icon_entypo="entypo-note" icon_lineicons="lineicon-banknote" icon_position="top" icon_style="style-normal" icon_color="#ffffff" icon_bg_color="#ffffff" icon_border_color="#16a085" css_animation_delay="0"]
<h5 style="text-align: center;"><span style="color: #ffffff;">INFINITE LAYOUTS</span></h5>
<p style="text-align: center;"><span style="color: #ffffff;">Etiam sollicitudin leo sit amet eleifend molestie. Donec pretium elit eget quam hendrerit, quis molestie nibh pretium. Class aptent taciti sociosqu ad litora torquent per conubia nostra</span></p>
[/md_box_icon][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]